// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV1hUnTWwzj6uolQxVqeyvLCDVyvVf268',
    appId: '1:193789014248:web:0c5698b1f99d649080595d',
    messagingSenderId: '193789014248',
    projectId: 'musiq-107d8',
    authDomain: 'musiq-107d8.firebaseapp.com',
    storageBucket: 'musiq-107d8.appspot.com',
    measurementId: 'G-ZMYEBM4K5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEPdHPY5uL0uBX4igXTmpya-I5qQNHc98',
    appId: '1:193789014248:android:d5323bd32288122f80595d',
    messagingSenderId: '193789014248',
    projectId: 'musiq-107d8',
    storageBucket: 'musiq-107d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4JZrYgDLdRFZ9h2IjDHWcneUfNEnzS3w',
    appId: '1:193789014248:ios:7de11a54fe7644ee80595d',
    messagingSenderId: '193789014248',
    projectId: 'musiq-107d8',
    storageBucket: 'musiq-107d8.appspot.com',
    iosBundleId: 'com.example.musiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4JZrYgDLdRFZ9h2IjDHWcneUfNEnzS3w',
    appId: '1:193789014248:ios:7de11a54fe7644ee80595d',
    messagingSenderId: '193789014248',
    projectId: 'musiq-107d8',
    storageBucket: 'musiq-107d8.appspot.com',
    iosBundleId: 'com.example.musiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV1hUnTWwzj6uolQxVqeyvLCDVyvVf268',
    appId: '1:193789014248:web:925625eba61eea9380595d',
    messagingSenderId: '193789014248',
    projectId: 'musiq-107d8',
    authDomain: 'musiq-107d8.firebaseapp.com',
    storageBucket: 'musiq-107d8.appspot.com',
    measurementId: 'G-V22M2L625R',
  );
}
