name: musiq
description: "A Music app."
publish_to: 'none' 

version: 1.5.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.1
  http: ^1.2.2
  audio_metadata_reader: ^0.0.6
  
  bloc: ^8.1.4
  audio_video_progress_bar: ^2.0.3
  shimmer: ^3.0.0
  shared_preferences: ^2.2.3
  lottie: ^3.1.2
  cloud_firestore: ^5.1.0
  url_launcher: ^6.3.0
  url_launcher_windows: ^3.1.2
  html: ^0.15.4
  encrypt: ^5.0.3
  cached_network_image: ^3.4.1
  google_nav_bar: ^5.0.6
  uni_links2: ^0.6.0+2
  audio_service: ^0.18.15
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  just_audio: ^0.9.40
  just_audio_windows: ^0.2.2
  carousel_slider: ^5.0.0
  fluttertoast: ^8.2.8
  package_info_plus: ^8.1.0
  permission_handler: ^11.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.11
  
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/logo/

  fonts:
    - family: LED-Dot-Matrix
      fonts:
        - asset: assets/fonts/LED Dot-Matrix.ttf
        
    - family: Nothing 
      fonts:
        - asset: assets/fonts/nothing.ttf
       
